// <auto-generated />
using System;
using MasplusCards.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MasplusCards.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260729065147_AddStripeIdsToPlanAndEmpresa")]
    partial class AddStripeIdsToPlanAndEmpresa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MasplusCards.Api.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("admins", (string)null);
                });

            modelBuilder.Entity("MasplusCards.Api.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Nombre")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Telefono")
                        .IsUnique();

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("MasplusCards.Api.Models.DiscountCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("FechaExpiracion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_expiracion");

                    b.Property<int?>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("plan_id");

                    b.Property<string>("TipoDescuento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipo_descuento");

                    b.Property<int>("UsosActuales")
                        .HasColumnType("int")
                        .HasColumnName("usos_actuales");

                    b.Property<int?>("UsosMaximos")
                        .HasColumnType("int")
                        .HasColumnName("usos_maximos");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("PlanId");

                    b.ToTable("discount_codes", (string)null);
                });

            modelBuilder.Entity("MasplusCards.Api.Models.DiscountCodeRedemption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("DiscountCodeId")
                        .HasColumnType("int")
                        .HasColumnName("discount_code_id");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int")
                        .HasColumnName("empresa_id");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("DiscountCodeId", "EmpresaId")
                        .IsUnique();

                    b.ToTable("discount_code_redemptions", (string)null);
                });

            modelBuilder.Entity("MasplusCards.Api.Models.Diseno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("CodigoRegistro")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("codigo_registro");

                    b.Property<string>("ColorPrimario")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("color_primario");

                    b.Property<string>("ColorSecundario")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("color_secundario");

                    b.Property<string>("ColorTexto")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("color_texto");

                    b.Property<string>("Configuracion")
                        .HasColumnType("json")
                        .HasColumnName("configuracion");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("descripcion");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int")
                        .HasColumnName("empresa_id");

                    b.Property<string>("FondoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("fondo_url");

                    b.Property<string>("IconoSello")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("icono_sello");

                    b.Property<string>("Logo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("logo");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("SellosRequeridos")
                        .HasColumnType("int")
                        .HasColumnName("sellos_requeridos");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("int")
                        .HasColumnName("template_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipo");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("Vencimiento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("vencimiento");

                    b.HasKey("Id");

                    b.HasIndex("CodigoRegistro")
                        .IsUnique();

                    b.HasIndex("EmpresaId");

                    b.HasIndex("TemplateId");

                    b.ToTable("disenos", (string)null);
                });

            modelBuilder.Entity("MasplusCards.Api.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int?>("DisenoActivoId")
                        .HasColumnType("int")
                        .HasColumnName("diseno_activo_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<string>("Logo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("logo");

                    b.Property<string>("Nombre")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<int?>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("plan_id");

                    b.Property<DateTime?>("PlanRenuevaEl")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("plan_renueva_el");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("stripe_customer_id");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("stripe_subscription_id");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("DisenoActivoId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PlanId");

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("MasplusCards.Api.Models.PassRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceLibraryIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("device_library_identifier");

                    b.Property<string>("PushToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("push_token");

                    b.Property<int>("TarjetaId")
                        .HasColumnType("int")
                        .HasColumnName("tarjeta_id");

                    b.HasKey("Id");

                    b.HasIndex("TarjetaId");

                    b.HasIndex("DeviceLibraryIdentifier", "TarjetaId")
                        .IsUnique();

                    b.ToTable("pass_registrations", (string)null);
                });

            modelBuilder.Entity("MasplusCards.Api.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("Caracteristicas")
                        .HasColumnType("json")
                        .HasColumnName("caracteristicas");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Destacado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("destacado");

                    b.Property<int?>("LimiteDisenos")
                        .HasColumnType("int")
                        .HasColumnName("limite_disenos");

                    b.Property<int?>("LimiteTarjetas")
                        .HasColumnType("int")
                        .HasColumnName("limite_tarjetas");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("int")
                        .HasColumnName("orden");

                    b.Property<decimal>("PrecioMensual")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_mensual");

                    b.Property<string>("StripePriceId")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("stripe_price_id");

                    b.HasKey("Id");

                    b.ToTable("planes", (string)null);
                });

            modelBuilder.Entity("MasplusCards.Api.Models.Tarjeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppleSerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apple_serial_number");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<string>("CodigoQr")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("codigo_qr");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("CuponRedimido")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("cupon_redimido");

                    b.Property<int>("DisenoId")
                        .HasColumnType("int")
                        .HasColumnName("diseno_id");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<int>("PremiosCanjeados")
                        .HasColumnType("int")
                        .HasColumnName("premios_canjeados");

                    b.Property<int>("SellosActuales")
                        .HasColumnType("int")
                        .HasColumnName("sellos_actuales");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("WalletTipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("wallet_tipo");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("CodigoQr")
                        .IsUnique();

                    b.HasIndex("DisenoId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("tarjetas", (string)null);
                });

            modelBuilder.Entity("MasplusCards.Api.Models.TarjetaLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("accion");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("descripcion");

                    b.Property<int?>("SellosAgregados")
                        .HasColumnType("int")
                        .HasColumnName("sellos_agregados");

                    b.Property<int>("TarjetaId")
                        .HasColumnType("int")
                        .HasColumnName("tarjeta_id");

                    b.HasKey("Id");

                    b.HasIndex("TarjetaId");

                    b.ToTable("tarjeta_logs", (string)null);
                });

            modelBuilder.Entity("MasplusCards.Api.Models.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<int?>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("admin_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estructura")
                        .HasColumnType("json")
                        .HasColumnName("estructura");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("PreviewImg")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("preview_img");

                    b.Property<string>("TipoRecompensa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipo_recompensa");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("templates", (string)null);
                });

            modelBuilder.Entity("MasplusCards.Api.Models.Cliente", b =>
                {
                    b.HasOne("MasplusCards.Api.Models.Empresa", "Empresa")
                        .WithMany("Clientes")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("MasplusCards.Api.Models.DiscountCode", b =>
                {
                    b.HasOne("MasplusCards.Api.Models.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("MasplusCards.Api.Models.DiscountCodeRedemption", b =>
                {
                    b.HasOne("MasplusCards.Api.Models.DiscountCode", "DiscountCode")
                        .WithMany("Redenciones")
                        .HasForeignKey("DiscountCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MasplusCards.Api.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiscountCode");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("MasplusCards.Api.Models.Diseno", b =>
                {
                    b.HasOne("MasplusCards.Api.Models.Empresa", "Empresa")
                        .WithMany("Disenos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MasplusCards.Api.Models.Template", "Template")
                        .WithMany("Disenos")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Empresa");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("MasplusCards.Api.Models.Empresa", b =>
                {
                    b.HasOne("MasplusCards.Api.Models.Diseno", "DisenoActivo")
                        .WithMany()
                        .HasForeignKey("DisenoActivoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MasplusCards.Api.Models.Plan", "Plan")
                        .WithMany("Empresas")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DisenoActivo");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("MasplusCards.Api.Models.PassRegistration", b =>
                {
                    b.HasOne("MasplusCards.Api.Models.Tarjeta", "Tarjeta")
                        .WithMany("PassRegistrations")
                        .HasForeignKey("TarjetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarjeta");
                });

            modelBuilder.Entity("MasplusCards.Api.Models.Tarjeta", b =>
                {
                    b.HasOne("MasplusCards.Api.Models.Cliente", "Cliente")
                        .WithMany("Tarjetas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MasplusCards.Api.Models.Diseno", "Diseno")
                        .WithMany("Tarjetas")
                        .HasForeignKey("DisenoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MasplusCards.Api.Models.Empresa", "Empresa")
                        .WithMany("Tarjetas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Diseno");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("MasplusCards.Api.Models.TarjetaLog", b =>
                {
                    b.HasOne("MasplusCards.Api.Models.Tarjeta", "Tarjeta")
                        .WithMany("Logs")
                        .HasForeignKey("TarjetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarjeta");
                });

            modelBuilder.Entity("MasplusCards.Api.Models.Template", b =>
                {
                    b.HasOne("MasplusCards.Api.Models.Admin", "Admin")
                        .WithMany("Templates")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("MasplusCards.Api.Models.Admin", b =>
                {
                    b.Navigation("Templates");
                });

            modelBuilder.Entity("MasplusCards.Api.Models.Cliente", b =>
                {
                    b.Navigation("Tarjetas");
                });

            modelBuilder.Entity("MasplusCards.Api.Models.DiscountCode", b =>
                {
                    b.Navigation("Redenciones");
                });

            modelBuilder.Entity("MasplusCards.Api.Models.Diseno", b =>
                {
                    b.Navigation("Tarjetas");
                });

            modelBuilder.Entity("MasplusCards.Api.Models.Empresa", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Disenos");

                    b.Navigation("Tarjetas");
                });

            modelBuilder.Entity("MasplusCards.Api.Models.Plan", b =>
                {
                    b.Navigation("Empresas");
                });

            modelBuilder.Entity("MasplusCards.Api.Models.Tarjeta", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("PassRegistrations");
                });

            modelBuilder.Entity("MasplusCards.Api.Models.Template", b =>
                {
                    b.Navigation("Disenos");
                });
#pragma warning restore 612, 618
        }
    }
}
